version: '2'
services:
    db:
        image: mariadb:latest
        command: mysqld --innodb-buffer-pool-size=20M
        volumes:
          - "appcode-logs:/var/log:rw"
          - ./data/backup:/backup
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: php7-fpm
        links:
            - db
            - memcached
            - redis
            - elk
            - mailcatcher
        environment:
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=10.254.254.254
        ports:
            - 9100:9000
        volumes:
            - "appcode-src:/var/www:rw"
            - "appcode-logs:/var/log:rw"

    nginx:
        build: nginx
        links:
            - php 
        ports:
            - 8080:80
        volumes:
            - "appcode-src:/var/www:rw"
            - "appcode-logs:/var/log:rw"

    memcached:
        image: memcached:alpine
        ports:
            - "11211:11211"
        mem_limit: 1g
        command: memcached -m 1024m

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    mailcatcher:
        build: mailcatcher
        ports:
            - "1025:1025"
            - "8070:1080"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8090:80"
        links:
            - db
        environment:
            PMA_USER: 'root'
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    elk:
        image: willdurand/elk
        ports:
            - 8060:80
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - "appcode-logs:/var/log:rw"
            - "appcode-src:/var/www:rw"

volumes:
    appcode-src:
        external: true
    appcode-logs:
        external: true
